---
version: 1.0.0
events:
  build:
    steps:
      - behaviors:
          type: script
          script:
            - set -ex
            - echo "Hello Kevin Hankens master after 7-2."
            - echo $MY_VAR_3
            - echo $MY_VAR_4
            - echo "Master commit after PR 6."
            - echo "PR 7 commit. updated 7."
