---
version: 1.0.0
events:
  build:
    steps:
      - behaviors:
          type: script
          script:
            - set -ex
            - echo "Hello Kevin Hankens from master. Update 4."
            - echo "Hello Kevin Hankens from Prs."
