---
version: 1.0.0
events:
  build:
    steps:
      - behaviors:
          type: script
          script:
            - set -ex
            - cat file.master.text
            - cat file.pr.text
       
